# Generated by Django 5.1.2 on 2024-10-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=50)),
                ('guess', models.CharField(max_length=5)),
                ('word', models.CharField(max_length=5)),
                ('green', models.IntegerField(default=0)),
                ('yellow', models.IntegerField(default=0)),
            ],
        ),
    ]
